#!/bin/bash

# Stops accidental commits to master

cd ../../../

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" == "master" ]]; then
	echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
	echo "If so, commit with --no-verify to bypass this pre-commit hook."
	exit 1
fi

exit 0